---
title: "test"
author: "mkn43"
date: "2/25/2022"
output: html_document
---
```{r}
library(tidyverse)
library(ggplot2)
library(dplyr)
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r}
urbanlong <- urban %>%
pivot_longer(cols=c("unemployment_rate_hispanic_or_latino_origin_of_any_race", "unemployment_rate_asian_alone", "unemployment_rate_white_alone", "unemployment_rate_black_or_african_american_alone", "total_unemployment_percent"),
               names_to = "race",
               values_to = "unemployment_rates")
urbanlong %>%
  ggplot()+
geom_line (mapping = aes(y = unemployment_rates, x = city_population, color=race),
           size=0.5, width = 10) +
  labs(title="Unemployment Trends",
       subtitle="by Race and Ethnicity",
       caption="Data from Urban Institute, 2018",
  y= "Unemployment Rates",
  colour= "Race and Ethnicity") +
  theme_minimal() +
  theme(legend.key.width = unit(0.5, 'cm'), legend.text = element_text(size=7)) +
  scale_x_continuous(name = "City Population")

```