---
title: "Assignment 4: Data Visualization, Markdown, and Git"
author: "Shelby Lauter & Maitreyi Natarajan"
date: "2/22/2022"
output: html_document
---

## Built Environment Health Equity Data
[Data Source](https://datacatalog.urban.org/dataset/72-small-and-medium-size-cities-built-environment-and-health-equity-dataset)

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(readxl)
library(ggplot2)
library(dplyr)

urban <- read_csv("health.equity.data.2.csv") %>%
    janitor::clean_names()

```
### Graph 1: Unemployment by Race and Ehtnicity

```{r graph1, warning = FALSE}
urban %>%
  ggplot()+
geom_line (mapping = aes(x = city_population, y = total_unemployment_percent), color="#CC6666",size=1)+
  geom_line (mapping = aes(x = city_population, y= unemployment_rate_hispanic_or_latino_origin_of_any_race), color="#9999CC", size=1)+
  geom_line (mapping = aes(x = city_population, y= unemployment_rate_asian_alone), color="#800080", size=1)+
  geom_line (mapping = aes(x = city_population, y= unemployment_rate_white_alone), color="#FFDB58", size=1)+
   geom_line (mapping = aes(x = city_population, y= unemployment_rate_black_or_african_american_alone), color="#00FF00", size=1)+
  labs(title="Unemployment Trends",
       subtitle="by Race and Ethnicity",
       caption="Data from Urban Institute, 2018",
  y="Unemployment Rates",
  x="City Population",
  colour= "Race and Ethnic") +
  scale_color_manual(name = "Race and Ethnicities", values = c("Total Unemployment Percent" = "#CC6666", "Hispanic or Latino Origin of Any Race" = "#9999CC", "Asian" = "#800080", "White" = "#FFDB58", "Black or African American" = "#00FF00"))+
    theme(
    plot.title = element_text(hjust = 0.5),
    plot.subtitle = element_text(hjust = 0.5)
    ) 

```


### Graph 2: Unemployment vs. Opioid Deaths

```{r graph2, warning = FALSE}
urban %>%
  ggplot(mapping = aes(y = total_unemployment_percent, x = opioid_overdose_deaths)) +
  geom_point(
    color = "orange", position = "jitter", size = 1.75, alpha = 0.9) +
  geom_smooth(
    color = "firebrick") + 
    scale_x_log10() +
  labs(title = "Unemployment vs. Opioid Deaths",
       x = "Number of opioid overdose deaths per 100,000 people (2017)",
       y = "Total unemployment (Percent)", 
       caption = "Data from Urban Institute, 2018") +
  theme(
    plot.title = element_text(hjust = 0.5)) 

```














